# Admin Registration and Login APIs
### Admin Registration (Controlled)
POST http://localhost:5000/api/auth/signup
Content-Type: application/json
Accept: application/json
Origin: http://localhost:3000

{
  "name": "Yamlak Negash",
  "email": "yamlaknegash96@gmail.com",
  "password": "12348765"
}