# Admin Registration and Login APIs
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "name": "Yamlak Negash",
    "email": "yamlaknegash96@gmail.com",
    "password": "12348765",
    "role": "admin"
}